### PR TITLE
Workaround to remove cxn information

### LINKED ISSUE #6: AttributeError at Fairy.__str__ of connection object
I'm using pika==0.10.0 and pika-pool==0.1.3.

When calling Fairy \__str\__ , there's an Error raise in this line:
('cxn', '{0}:{1}/{2}'.format(self.cxn.params.host, self.cxn.params.port, self.cxn.params.virtual_host)),
AttributeError: 'BlockingConnection' object has no attribute 'params'

The BlockingConnection does not params attribute, could you take a look at that? Thanks.

### PR DESCRIPTION
**Pull request by lachesis**
This fixes #6, introduced in #2.

### CODE REVIEW

**Comment by bninja** [comment]
@lachesis looks like its just buried in some `._impl` so fixed w/ https://github.com/bninja/pika-pool/pull/11
